version: '2'

services:
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=uns
    ports:
      - "9000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pmf:
    image: pmf
    container_name: pmf
    build:
      context: .
      dockerfile: ./fakultet/Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"

  uns:
    image: uns
    container_name: uns
    build:
      context: .
      dockerfile: ./uns/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      pg:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/uns
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
