# Generated by Django 3.2.12 on 2023-01-25 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=100)),
                ('jmbg', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='ftn/images')),
                ('birthDate', models.DateField(blank=True, default=datetime.date.today)),
                ('title', models.CharField(blank=True, choices=[('Research assistant professor', 'Research assistant professor'), ('Research associate professor', 'Research associate professor'), ('Research professor', 'Research professor')], default='Research professor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=100)),
                ('jmbg', models.CharField(max_length=20)),
                ('birthDate', models.DateField(blank=True, default=datetime.date.today)),
                ('indexNumber', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ftn/images')),
            ],
        ),
    ]
