# Generated by Django 3.2.12 on 2023-01-22 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='birthDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='birthDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
