# Generated by Django 3.2.12 on 2023-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='title',
            field=models.CharField(blank=True, choices=[('Research assistant professor', 'Research assistant professor'), ('Research associate professor', 'Research associate professor'), ('Research professor', 'Research professor')], default='Research professor', max_length=50),
        ),
    ]
