# Generated by Django 3.2.12 on 2023-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMF', '0002_auto_20230122_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
