name: Upload to DockerHub
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the docker image uns
        run: docker build -tag andreasaboc/uns -f uns/Dockerfile .
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/uns
